### ISSUE TITLE
rate limit for your current plan is exceeded

### ISSUE THREAD

**Issue by RubenBenBen** [QuickBlox/quickblox-ios-sdk#1035]
Hi guys, I know this is not the right place to post this issue, but I already wrote this question to your support team two times more than a week ago and there is no response at all, and I need to clarify this asap. I've recently got two email notifications that "rate limit for your current plan (starter) is exceeded" . As I checked in [plans](https://quickblox.com/plans/) I'm not exceeding anything, I don't send any notifications and I don't use chat messages, my app is just using video calls from quickBlox, but there is no limitation to video calls as I see it. So I wonder why am I getting the email about exceeding? Is there any other limitation not mentioned in plans? my app ID is 70224. Thanks

**Comment by Raikerian** [comment]
Hi, while I don't know what caused it in your specific case, as I don't have access to that information, I can, however, inform you that audio/video calls are using chat messages in order to send and receive signals about themselves. By default QuickbloxWebRTC framework sending 1 call signal (message) per 5 seconds when you are calling someone. You can set this value in `QBRTCConfig`:
```
/**
 *  Set dialing time interval
 *
 *  Indicates how often we send notifications to your opponents about your call
 *
 *  Default value: 5 seconds
 *  Minimum value: 3 seconds
 *  @param dialingTimeInterval time in seconds
 */
+ (void)setDialingTimeInterval:(NSTimeInterval)dialingTimeInterval;
```

So this is a possible issue if you have a lot of calls simultaneously in your free plan. You can calculate how many you can perform according to the information I have provided above.

**Comment by RubenBenBen** [comment]
Thanks, now I get it. Is there a way to handle that? like if I exceed the limit of 20 calls/second and the call request gets rejected, to try again on another second.

**Comment by Raikerian** [comment]
There is no way to handle this within webrtc, and you shouldn't really be bothered. If some messages exceed the plan, they will just fail to send. You can up dialling time interval a bit if you want to lighten your message network.

**Comment by RubenBenBen** [comment]
yeah already did that, thanks for clarifying.
