### ISSUE TITLE
Can I update 'Quickblox-WebRTC', '~> 2.6' to  2.7

### ISSUE THREAD

**Issue by vineeshtp** [QuickBlox/quickblox-ios-sdk#1041]
I already implemented QuickBlox audio and video chat.

Like below issue thread,

[https://github.com/QuickBlox/quickblox-ios-sdk/issues/733](https://github.com/QuickBlox/quickblox-ios-sdk/issues/733)

facing some issue with MainThread checker and Automatically video call drop in `'Quickblox-WebRTC', '~> 2.6`

I used cocoapods for implementing the QuickBlox.
Can I update the pod file with `'Quickblox-WebRTC', '~> 2.7` directly ?
Do I need to change any existing code?

 - [ ] I have read the [Documentation](https://quickblox.com/developers/IOS)
 - [ ] I have searched for a similar issue in the [project](https://github.com/QuickBlox/quickblox-ios-sdk/issues) and found none

**Environment details**

Info                           | Value                                       |
-------------------------------|---------------------------------------------|
iOS Version                    | e.g. 8.0                                    |                                          
Quickblox iOS SDK version      | e.g. 2.7.6                                  |
QuickbloxWebRTC SDK version    | e.g. 2.2.1                                  |                               
Xcode Version                  | e.g. Xcode 8.1                              |
Repro with our demo sample     | e.g. does it happen with our demo sample?   |

**Did this work before?**

**Expected behavior**

**Actual behavior**

**Logs**

*Please use the following template for logs:*

To enable full logs use the following code:
```objc
[QBSettings setLogLevel:QBLogLevelDebug];
[QBSettings enableXMPPLogging];
```

<details>
<summary>Title for logs </summary>

```logos

// Your logs here

```

</details>

**Steps to reproduce the behavior**

**Any others comments**

**Comment by Raikerian** [comment]
Hi,

You can see 2.7 changelogs here: https://quickblox.com/developers/Sample-webrtc-ios#Framework_changelog

According to it, we no longer support iOS 8 with the webrtc framework. So this might be an issue for you if your project target is lower than iOS 9. Other than that nothing was removed, but you might need to check some new features though.
If dropped iOS 8 is a problem for you, you will have to stay on 2.6, but I at least recommend you to update to 2.6.2. The issue with MainThread checker is just a warning for using applicationState in the background thread, as it might be incorrect, so it can be ignored for now (fixed in 2.7 though).
