### ISSUE TITLE
error: Request failed: unauthorized (401) on signup user step (Version 2.17.1)

### ISSUE THREAD

**Issue by YogendraPatel** [QuickBlox/quickblox-ios-sdk#1070]
I have working on quickblox framework integration from last 2 days, i follow https://quickblox.com/developers/IOS link for integration, but unfortunately i stop at signup user step

**==>Signup code**

QBUUser *user=[[QBUUser alloc] init];
user.login=@"abc";
user.password=@"12345678";

[QBRequest signUp:user successBlock:^(QBResponse * _Nonnull response, QBUUser * _Nonnull tUser) {
                NSLog(@"Successfully signup:-%@",tUser);
            } errorBlock:^(QBResponse * _Nonnull response) {
                NSLog(@"Error in signup:- %@",response);
            }];

**==>Every time it will return**

error: Request failed: unauthorized (401)
reasons: {
    errors =     {
        base =         (
            "Required session does not exist"
        );
    };
}

Please anybody have solution then help me

Thanks in advance

**Comment by KrishnaPatell** [comment]
I'm also facing this issue. If anyone have solution then let us know.

**Comment by QB-vladyslav-vyshniak** [comment]
Hello, dear @YogendraPatel @KrishnaPatell 

Thank you for contacting QuickBlox support.

Authorization is missing or incorrect. 
Possible causes:
1. A User tries to authorize with the wrong login and password 
2. A user uses the invalid session token. 

Please, could you confirm that this issue is still relevant for you? 

If you have any additional questions, please let us know.

**Comment by QB-vladyslav-vyshniak** [comment]
Dear @YogendraPatel 

The status of the ticket changed to "Closed" due to the absence of the reply from you.
If you have any additional questions, please let us know.
