### ISSUE TITLE
XMPPError: internal-server-error - wait

### ISSUE THREAD

**Issue by timeetdev1** [QuickBlox/quickblox-ios-sdk#1079]
@Julls-03 We are using QB SDK both for Android (3.8.1) and for iOS (2.17.1).
Since yesterday we are getting the following error:

 joinDialog: com.quickblox.core.exception.QBResponseException: XMPPError: internal-server-error - wait

Any idea? 
I Read the ticket regarding QB shutting down but I also heard that this is faked news..

**Comment by math609** [comment]
You are not the only one having this issue. We have the same problem here.

**Comment by QB-vladyslav-vyshniak** [comment]
Hello, dear @timeetdev1 @math609 

Thank you for contacting QuickBlox support. 
Take our apologies for the delay in reply.

You faced this issue, because we had maintenance on our instances at that time.
Currently, all is working well and you can test it.

If you have any additional questions, please, let me know.

**Comment by math609** [comment]
Let's make something abundantly clear, your customer service is slow and I'm starting to question if you have any unit testing in your own back end. In the last 6 months, your service failed 5 times and each time your turnover time was of 12h+ minimum. Your worst-case scenario was around 36h. In our modern days, it is simply unacceptable.And I'm not even including your unannounced migration that last for 1 to 3 hours.

One last thing, just to set the record straight. On August 18th the issue was not a "maintenance" it was a failure on XMPP on your end generating a server failure and it was confirmed by your own support team. Oh and to add some irony the service is not working at the moment!

**Comment by tuna25** [comment]
@QB-vladyslav-vyshniak  since yesterday... both our prod apps affected

**Comment by QB-vladyslav-vyshniak** [comment]
@tuna25
Could you please create a new ticket in our QB customer support portal and provide us with your "Application ID".
Link: https://assist.quickblox.com/index.php?/Tickets/Submit
Our DevOps team will investigate the issue.
Because all works as expected on our Shared instance.

**Comment by QB-vladyslav-vyshniak** [comment]
Dear @math609 

Thank you for your honest feedback - this is useful for improving of our services.
As there was discussed on a call team faced with the unexpected issue during a software update and we will provide an update on further maintenance via blog  https://quickblox.com/blog/.

In case of additional questions or support requests, please, submit a ticket to customer support portal https://assist.quickblox.com/index.php?/Tickets/Submit

**Comment by QB-vladyslav-vyshniak** [comment]
Dear @tuna25 

It was maintenance on our "Shared" instance, all issues have been resolved on 16 of January.
Currently, all is working well. Next time you can check our blog, there we inform the customers about any maintenances, updates, releases, etc: https://quickblox.com/blog/

**Comment by tuna25** [comment]
@QB-vladyslav-vyshniak 

Ok I tried sir

it also not working

are you guys even know what is going on with your system? 

<img width="1241" alt="submit_a_ticket_-_powered_by_kayako_help_desk_software" src="https://user-images.githubusercontent.com/40854633/51629929-7d821580-1f51-11e9-9f8f-5dee4d67eda0.png">

**Comment by tuna25** [comment]
@QB-vladyslav-vyshniak  man you really driving me nuts???
<img width="1111" alt="banners_and_alerts_and_quickblox_-_powered_by_kayako_help_desk_software" src="https://user-images.githubusercontent.com/40854633/51685999-2be09600-1ff8-11e9-89f6-d783e530bea1.png">

**Comment by QB-vladyslav-vyshniak** [comment]
Dear @tuna25 

Please, could you try to submit a ticket one more time, we disabled the registration process, so you can proceed with it without registration.
From our side, the process of registration works as expected too, so I can provide you with the video.

**Comment by imran-samed** [comment]
@timeetdev1 @math609 @QB-vladyslav-vyshniak @tuna25 @soulfly 

Hi 

Is anyone get solution for this.

**Comment by math609** [comment]
@imran-samed There isn't any. The issue is on their end. Honestly, the solution is to move to another service!

**Comment by QB-vladyslav-vyshniak** [comment]
Hello, dear @imran-samed @math609 

This is a known issue for QuickBlox developers team. 
During last week users on QB Shared instance faced with the service degradation due to traffic attacks from UAE, please, check an article about it on our blog: https://quickblox.com/blog/
Currently, our developers are resolving the issue and supporting stable work of Shared instance.

**Comment by QB-vladyslav-vyshniak** [comment]
Dear @imran-samed 

Could you please provide us with information about how you are facing the issue?
Because as I know - you are QuickBlox Enterprise customer and have your dedicated instance.

**Comment by QB-vladyslav-vyshniak** [comment]
Dear @math609 

Soon, you will use QB dedicated instance, please, enjoy the best service and stable work with QB Enterprise.
