### ISSUE TITLE
Show marked messages in chat

### ISSUE THREAD

**Issue by dipendrapulse** [QuickBlox/quickblox-ios-sdk#1157]
**New Issue Checklist**

 - [ ] I have read the [Documentation](https://quickblox.com/developers/IOS)
 - [ ] I have searched for a similar issue in the [project](https://github.com/QuickBlox/quickblox-ios-sdk/issues) and found none

**Environment details**

Info                           | Value                                       |
-------------------------------|---------------------------------------------|
iOS Version                    | 12.2                                    |                                          
Quickblox iOS SDK version      | 2.16                                  |
QuickbloxWebRTC SDK version    | e.g. 2.2.1                                  |                               
Xcode Version                  | e.g. Xcode 10.2.1                              |

Hi Quickblox Team,

I am using the Chatviewcontroller of sample chat to show all chat listing of the app.
Now I want to mark the messages which are read by the Opponent. 

I see we have method chatDidReadMessageWithID is called when the message is read by the opponent and again this method call didUpdateMessage: method which is called for other scenarios too.

Please advise how to integrate mark message to read feature in chatviewcontroller.m

**Comment by QB-nikolay-zolotarov** [comment]
This is Nikolay from QuickBlox support.

The issue was closed as it is outdated.

If it is still relevant, feel free to open a new issue.

Have a nice day.

**Comment by QB-nikolay-zolotarov** [comment]
Hello QuickBlox customer,

This is Nikolay from QuickBlox support.

The issue was closed as it is outdated.

Please check the relevant section of our documentation here:
[https://docs.quickblox.com/docs/ios-chat-messaging#mark-message-as-read](https://docs.quickblox.com/docs/ios-chat-messaging#mark-message-as-read)

Also, please update the SDK to the latest version:
[https://github.com/QuickBlox/quickblox-ios-sdk/releases/tag/2.17.10](https://github.com/QuickBlox/quickblox-ios-sdk/releases/tag/2.17.10)

Additionally, please check our new samples:
[https://docs.quickblox.com/docs/code-samples#chat-samples](https://docs.quickblox.com/docs/code-samples#chat-samples)

If it is still relevant after reviewing the updated information, feel free to open a new issue.

Have a nice day.
