### ISSUE TITLE
Video sharing issue for receiver

### ISSUE THREAD

**Issue by dipendrapulse** [QuickBlox/quickblox-ios-sdk#1162]
**New Issue Checklist**

 - [ ] I have read the [Documentation](https://quickblox.com/developers/IOS)
 - [ ] I have searched for a similar issue in the [project](https://github.com/QuickBlox/quickblox-ios-sdk/issues) and found none

**Environment details**

Info                           | Value                                       |
-------------------------------|---------------------------------------------|
iOS Version                    | e.g. 12.2                                    |                                          
Quickblox iOS SDK version      | e.g. 2.16                                  |
QuickbloxWebRTC SDK version    | e.g. 2.2.1                                  |                               
Xcode Version                  | e.g. Xcode 12.2.1                              |

Hi Quickblox Team,

I am integrating a video sharing feature in ios SDK for that I am using Chatviewcontroller class of sample code. All is working fine except when the receiver is on chat screen & receives the video then the cell's thumb(show video thumbnail) is not updated.

I am making change in following method
- (void)collectionView:(QMChatCollectionView *)collectionView configureCell:(UICollectionViewCell *)cell forIndexPath:(NSIndexPath *)indexPath {

[[ServicesManager instance].chatService.chatAttachmentService.assetService loadAssetForAttachment:attachment messageID:message.ID completion:^(UIImage * _Nullable image, Float64 durationInSeconds, CGSize size, NSError * _Nullable error, BOOL cancelled ) {
[(id)cell setAttachmentImage:image]; //The image is not updated
[(id)cell setStrVideoURL:attachment.remoteURL.absoluteString];
[(QMBaseMediaCell*)cell setMediaHandler:self];
}

}

Although when I scroll up & down for 5 to 6 times then it works. Any help regarding this is appreciated.

**Comment by QB-nikolay-zolotarov** [comment]
This is Nikolay from QuickBlox support.

The issue was closed as it is outdated.

If it is still relevant, feel free to open a new issue.

Have a nice day.

**Comment by QB-nikolay-zolotarov** [comment]
Hello QuickBlox customer,

This is Nikolay from QuickBlox support.

The issue was closed as it is outdated.

Please check the relevant section of our documentation here:
[https://docs.quickblox.com/docs/ios-chat-messaging#send-message-with-attachment](https://docs.quickblox.com/docs/ios-chat-messaging#send-message-with-attachment)

Also, please update the SDK to the latest version:
[https://github.com/QuickBlox/quickblox-ios-sdk/releases/tag/2.17.10](https://github.com/QuickBlox/quickblox-ios-sdk/releases/tag/2.17.10)

Additionally, please check our new samples:
[https://docs.quickblox.com/docs/code-samples#chat-samples](https://docs.quickblox.com/docs/code-samples#chat-samples)

If it is still relevant after reviewing the updated information, feel free to open a new issue.

Have a nice day.
