### ISSUE TITLE
currentAudioDevice is deprecated

### ISSUE THREAD

**Issue by maughray** [QuickBlox/quickblox-ios-sdk#1237]
How can I change audio output if the method below is deprecated?
`QBRTCAudioSession.instance().currentAudioDevice = .speaker // WARNING: 'currentAudioDevice' is deprecated`

UPD:
Is this a good solution?
`try? AVAudioSession.sharedInstance().overrideOutputAudioPort(.speaker)`

**Comment by QB-maksym-pidhorbunskyi** [comment]
Hello @maughray,

Thank you for contacting QuickBlox support.

This issue is known and we will update our documentation as soon as possible.

You can find the code example from unreleased documentation below:

QBRTCAudioSession *audioSession = [QBRTCAudioSession instance];
AVAudioSessionPortOverride audioPort =
sender.selected == NO ? AVAudioSessionPortOverrideSpeaker : AVAudioSessionPortOverrideNone;
[audioSession overrideOutputAudioPort:audioPort];

Here is the changelog:

Updated the "QBRTCAudioSession" class for more convenient support for new iOS 13 and CallKit requirements.
/// New methods:
setActive: - activates the audio session if it isn't already active. Successful calls must be balanced with a setActive:NO when activation is no longer required. If not |active|, deactivates the audio session if one is active and this is the last balanced call. When deactivating, the AVAudioSessionSetActiveOptionNotifyOthersOnDeactivation option is passed to AVAudioSession.
isActive: - Detected whether the session is active based on results of calls to AVAudioSession.
overrideOutputAudioPort: - This method is a proxy for the associated methods on AVAudioSession.
setConfiguration: - Applies the configuration to the current session.
setConfiguration:active: - Convenience method that calls both setConfiguration and setActive.
/// Deprecated methods:
currentAudioDevice
initialized - Use 'isActive' instead.
initialize - Use 'setActive:' set to `YES` instead. Also can use audioSessionDidActivate: method.
initializeWithConfigurationBlock - Use 'setConfiguration:' or 'setConfiguration::active:' instead.
deinitialize - Use 'setActive:' set to `NO` instead. Also can use audioSessionDidDeactivate: method.

Please try to use the updated method and inform us whether it resolves the issue.

Looking forward to your reply.

**Comment by maughray** [comment]
The issue is solved. Thanks.

**Comment by shoaibHassanAttech** [comment]
@QB-maksym-pidhorbunskyi  can you provide a sample code replacement for  
`rtcAudioSession.initialize(configurationBlock: nil)`
because new sdk is asking for 'QBRTCAudioSessionConfiguration' type object.

Looking forward to your reply.

**Comment by maughray** [comment]
> @QB-maksym-pidhorbunskyi can you provide a sample code replacement for
> `rtcAudioSession.initialize(configurationBlock: nil)`
> because new sdk is asking for 'QBRTCAudioSessionConfiguration' type object in setActive method.
> 
> Looking forward to your reply.

```
let audioSession = QBRTCAudioSession.instance()
        audioSession.useManualAudio = true
        
        if !audioSession.isActive
        {
            let config = QBRTCAudioSessionConfiguration()
            config.categoryOptions.insert(.allowBluetooth)
            config.categoryOptions.insert(.allowBluetoothA2DP)
            config.categoryOptions.insert(.duckOthers)
            config.categoryOptions.insert(.allowAirPlay)
            config.mode = AVAudioSession.Mode.videoChat.rawValue
            
            // This method is initializing audio session with given config
            audioSession.setConfiguration(config, active: true)
        }
```

**Comment by shoaibHassanAttech** [comment]
@maughray  thank you.
