### ISSUE TITLE
How to send silent push notifications?

### ISSUE THREAD

**Issue by maughray** [QuickBlox/quickblox-ios-sdk#1271]
**New Issue Checklist**

 - [x] I have read the [Documentation](https://quickblox.com/developers/IOS)
 - [x] I have searched for a similar issue in the [project](https://github.com/QuickBlox/quickblox-ios-sdk/issues) and found none

QBMEvent and QBMPushMessage simply are not sent if "content-available" parameter is present. Is there a way to send silent notifications to some user? 

Thanks

**Comment by QB-nikolay-zolotarov** [comment]
@maughray Hello,

This is Nikolay from QuickBlox support.

We don’t have the feature of sending silent push notifications at this moment as well as information about it in the documentation.

According to feedback from our developers, we are going to implement this functionality as a core feature. However, there is no ETA due to other scheduled tasks.
