### ISSUE TITLE
500 Internal server error on Login

### ISSUE THREAD

**Issue by BCSingh** [QuickBlox/quickblox-ios-sdk#1299]
**New Issue Checklist**

 - [ Yes] I have read the [Documentation](https://quickblox.com/developers/IOS)
 - [Yes ] I have searched for a similar issue in the [project](https://github.com/QuickBlox/quickblox-ios-sdk/issues) and found none

**Environment details**

Info                           | Value                                       |
-------------------------------|---------------------------------------------|
iOS Version                    | 15.0                                    |                                          
Quickblox iOS SDK version      |   2.17.10                                  |
QuickbloxWebRTC SDK version    |    2.7.6                              |                               
Xcode Version                  |   13.0                             |
Repro with our demo sample     | Yes the same happens in demo sample   |

**Did this work before?**
YES, with another quickblox account.

**Expected behavior**
Quickblox login should succeed. 

**Actual behavior**
Quickblox login fails with 500 Internal server error. 

**After doing the Quickblox initialization, we are calling QBRequest.login**

```
        QBSettings.applicationID = CredentialsConstant.applicationID;
        QBSettings.authKey = CredentialsConstant.authKey
        QBSettings.authSecret = CredentialsConstant.authSecret
        QBSettings.accountKey = CredentialsConstant.accountKey
        QBSettings.autoReconnectEnabled = true
        QBSettings.keepAliveInterval = 30
        QBSettings.logLevel = QBLogLevel.nothing
        QBSettings.disableXMPPLogging()
        QBSettings.disableFileLogging()
        QBRTCConfig.setLogLevel(QBRTCLogLevel.nothing)
        QBRTCClient.initializeRTC()

QBRequest.logIn(withUserLogin: qbid, password: qbPwd, successBlock: { (response, user) in
            print(response)
 }) { (response) in
            print(response.error ?? "")
 }
```

<details>
<summary>Login throws 500 error with the following response.error printed </summary>

```
{
    errors =     {
        details = "Internal Server Error";
   };
}
```
</details>

**Steps to reproduce the behavior**
Do quickblox login using user login and password.

**Comment by QB-nikolay-zolotarov** [comment]
Hello @BCSingh ,

This is Nikolay from QuickBlox support.

The password should be at least 8 characters. 

Please try using another password and let me know if the issue is resolved.

If the issue persists, please provide me with the following points:
1. When did this issue happen? Did the issue happen before or after implementing recent changes into your code?
2. Is this issue intermittent or permanent?
3. Please provide me with full REST + XMPP logs as an attachment in .txt format. 
You can find out how to gather logs here: [Gathering logs guides - QuickBlox Help Center](https://help.quickblox.com/article/368-how-can-i-enable-quickblox-logs)
4. iPhone models (e.g. iPhone 12 Pro).

**Comment by QB-nikolay-zolotarov** [comment]
@BCSingh According to my check, there were temporary issues.

The issues should be resolved.

Please try reproducing it and let me know if everything works as expected.
