### ISSUE TITLE
Call does not hang up for receiver

### ISSUE THREAD

**Issue by sahilgarg156** [QuickBlox/quickblox-ios-sdk#1322]
The issue is when a receiver receives the call the connection gets established with the caller but does not disconnect for the receiver.
1. If the caller ends the call it gets disconnect for both the parties. (Works fine)
2. If receiver disconnects the call, it will only disconnect for the caller and not for the receiver. (Issue)

Now I have tested this scenario many times but I am not able to replicate the issue. It happens only for my client and we have tested it the following devices:
My devices: iPhone XR, 13 pro and XS
My client's device: iPhone XR, 13 and 8
We all are using the same iOS which is 15.5.
Quickblox iOS sdk version: 2.17.11

Please help me rectifying the issue and then I will fix it.

**Comment by QB-nikolay-zolotarov** [comment]
@sahilgarg156 We've reviewed the provided issue details and would like to ask you to clarify the following points:
1. When did this issue happen? Did the issue happen before or after implementing recent changes into your code?
2. Is this issue intermittent or permanent?
3. Please clarify if you used parts of our samples in your application. If yes, Swift or ObjC?
4. Please provide us with full REST + XMPP + WebRTC logs as an attachment to this ticket in .txt format. There should be logs from application start till request and "wrong" behavior for both caller and callee parts.
You can find out how to gather logs here: [Gathering logs guides - QuickBlox Help Center](https://help.quickblox.com/article/368-how-can-i-enable-quickblox-logs)

As we experienced a similar issue with our samples, we assume that it is related to the client-side implementation. We are going to release new samples next week or later where this issue is fixed.
You may check the samples repositories for updates:
https://github.com/QuickBlox/quickblox-ios-sdk
