### ISSUE TITLE
chatDidNotSendMessage not getting called when blocked user tries to send message in 1:1 chat

### ISSUE THREAD

**Issue by sourcebits-anand** [QuickBlox/quickblox-ios-sdk#135]
Use case:
 1. User1  blocks User2.
 2. User2 tries to send message to User1.

Expected result :
chatDidNotSendMessage should get called for User2

Actual result:
chatDidNotSendMessage not getting called for User2

Code:
 QBPrivacyItem *item = [[QBPrivacyItem alloc] initWithType:USER_ID valueForType:user.chatuserID.integerValue action:DENY];

QBPrivacyList *list = [[QBPrivacyList alloc] initWithName:@"Blocked" items:@[item]];
  [[QBChat instance] setPrivacyList:list];

**Comment by iSevenDays** [comment]
Hello. 

http://quickblox.com/developers/SimpleSample-chat_users-ios#Create_a_privacy_list_or_edit_existing_list

I think you have missed this section
Activate a privacy list
User can have multiple privacy lists, but active can be only one. In order to activate rules from a privacy list you must activate it by setting as default.

"Active" makes a list active for current chat session and "Default" makes it active for all further sessions so you don't need to activate it every time.




So you should
 [[QBChat instance] setDefaultPrivacyListWithName:@"public"];
[[QBChat instance] setActivePrivacyListWithName:@"public"];

**Comment by sourcebits-anand** [comment]
I was setting them after i initialise QBPrivacyList object but it seems like every time we  modify QBPrivacyList, we need to set  privacy list as default and active.

Code:
[[QBChat instance] setDefaultPrivacyListWithName:@"Blocked"];
[[QBChat instance] setActivePrivacyListWithName:@"Blocked"];
