### ISSUE TITLE
Last message is not deleted on deleting the dialog

### ISSUE THREAD

**Issue by manohar-techahead** [QuickBlox/quickblox-ios-sdk#1360]
If a dialog is deleted and then next time chat with a user is initiated, new dialog still shows last message in dialog listing whereas in detailed chat it does not show that message
![Simulator Screen Shot - iPhone 14 Pro Max - 2023-08-24 at 15 54 11](https://github.com/QuickBlox/quickblox-ios-sdk/assets/142577466/645d820e-a54a-40b4-ad0a-61210f5b059c)

**Comment by VladimirNybozhinsky** [comment]
Hi @manohar-techahead 
This is Vladimir from QuickBlox.

https://discord.gg/ZWZ3WpYZ9q

Please specify what type of dialog you are using? It's not clear from your description.

If you are using a private dialog, then this is absolutely expected behavior. Private conversations are not deleted from the server. You can even think of them in such a way that between all users in the system there have always been, are and will be private dialogues on the server.

And if the user deletes his private dialogue and then "creates" it again, he will receive the same dialogue from the server, which has the "last message" either from himself or from his opponent. And by the way, when a user deletes a private dialog, this does not mean that the opponent should delete it too (Depends on the application logic)

If you don't want to display the "last message" in this case, then you need to handle this case depending on the application idea.

For example, when you delete a private conversation and recreate it, you can send a "notification" message to it (for example, chatMessage.customParameters["notification_type" = "back_to_private_dialog") and save it on the server (for example, chatMessage .customParameters["save_to_history" ] = true) with a welcome text like: "Bob has joined the chat", and then this message will become the "last message". " and it will be displayed in the list of dialogues:


![image](https://github.com/QuickBlox/quickblox-ios-sdk/assets/43746573/33bae197-118b-4453-ace5-fde98ecf0fcc)


 and on the chat screen there will be something like this


![image](https://github.com/QuickBlox/quickblox-ios-sdk/assets/43746573/22ef3c78-20b4-4f5d-8e39-6180bc038285)
Best regards, Vladimir

https://discord.gg/ZWZ3WpYZ9q
