### ISSUE TITLE
contains bitcode and stopped at sending to app store

### ISSUE THREAD

**Issue by nobodyyu** [QuickBlox/quickblox-ios-sdk#1374]
**New Issue Checklist**

 - [O] I have read the [Documentation](https://quickblox.com/developers/IOS)
 - [O ] I have searched for a similar issue in the [project](https://github.com/QuickBlox/quickblox-ios-sdk/issues) and found none

**Environment details**

Info                           | Value                                       |
-------------------------------|---------------------------------------------|
iOS Version                    | 18.0                                    |                                          
Quickblox iOS SDK version      | 2.19.0                                  |
QuickbloxWebRTC SDK version    | 2.8.1                                  |                               
Xcode Version                  | Xcode 16 16A242d                              |
Repro with our demo sample     | e.g. does it happen with our demo sample?   |

**Did this work before?**
yes

**Expected behavior**
could be uploaded to app store

**Actual behavior**
logs show asset validation failed

**Logs**
"the execuable {sdk} contains bitcode {udid}"

To enable full logs use the following code:
none

**Steps to reproduce the behavior**

**Any others comments**

**Comment by IlliaChemolosov** [comment]
How to Fix “Invalid Executable” Error on App Store Upload

🚨 If you’re seeing this error:
“Invalid Executable. Executable App.app/Frameworks/QuickbloxWebRTC.framework/QuickbloxWebRTC contains bitcode” after updating to Xcode 16, it’s probably due to outdated libraries.

🔄 Fix: Update your libraries! Make sure you’re using QuickbloxWebRTC v3.1.0+.
