### ISSUE TITLE
Missed few parameters in QBChatMessage file

### ISSUE THREAD

**Issue by pratikpatan** [QuickBlox/quickblox-ios-sdk#1380]
**Missed few parameters in QBChatMessage file**

**Environment details**

Info                           | Value                                       |
-------------------------------|---------------------------------------------|
iOS Version                    | 18.1                                    |                                          
Quickblox iOS SDK version      | 2.20.0                                  |
QuickbloxWebRTC SDK version    | 3.1.0                                  |                               
Xcode Version                  | Xcode 16.1                              |
Repro with our demo sample     | e.g. does it happen with our demo sample? Yes  |

I want to show call duration with call state as new cell in Chat listing page. Currently, getting below response from Chat api.
I want callState, callType, callDuration, callee & caller in QBChatMessage class. (@interface QBChatMessage : NSObject <NSCoding, NSCopying>).

```
     {
            "_id" = 675a7e7eb7442632a2000003;
            attachments =             (
            );
            callDuration = 18;
            callState = 1;
            callType = 2;
            callee = 140565142;
            caller = 140565084;
            "chat_dialog_id" = 674d6fba6cf4cd3e0de41340;
            "created_at" = "2024-12-12T06:11:16Z";
            "date_sent" = 1733983876;
            "delivered_ids" =             (
                140565142,
                140565084
            );
            message = "Call notification";
            read = 1;
            "read_ids" =             (
                140565142,
                140565084
            );
            "recipient_id" = 140565142;
            "sender_id" = 140565084;
            sessionID = "ba4b674b-e7a6-4339-a184-5d9d7be870e8";
            "updated_at" = "2024-12-12T06:11:16Z";
        }
```

**Comment by IlliaChemolosov** [comment]
@pratikpatan Hello! Thank you for your message!

Regarding your request to include callState, callType, callDuration, callee, and caller in the QBChatMessage class, it seems this aligns more with a feature enhancement rather than an issue with the existing samples. To achieve your goal, we recommend checking out our [documentation on sending messages with extra data](https://docs.quickblox.com/docs/ios-chat-messaging#send-message-with-extra-data). This will guide you in customizing messages to include additional parameters.

If you’d like to discuss feature suggestions or get advice from our developer community, we invite you to join our [Discord server](https://discord.com/invite/aFpRptyz), where you can collaborate with other developers and QuickBlox team members.

For future reference, we kindly ask that GitHub issues remain focused on reporting bugs or errors in the provided samples. This helps us maintain clarity and prioritize fixing issues effectively.

Thank you for understanding, and let us know if you have any further questions!
