### ISSUE TITLE
Each Release come with breaking changes with Very little Information in Release Notes

### ISSUE THREAD

**Issue by itsaboutcode** [QuickBlox/quickblox-ios-sdk#232]
We are moving to Quickblox-WebRTC 2.1.1 (was 1.0.6). Now lots of things which don't work and there is no way for me to know which methods went where since change logs are very limited. Just wondering when you guys will documents your changes to make them effective?

Thanks.

**Comment by Pro100Andrey** [comment]
Hi @itsaboutcode !!!
We tried to keep as much portability in our SDK as we can, so we fully refactored only classes that can not be improved without full rearchitecture.

In order to replace old SDK and upgrade to the newest version consider doing the following:
In order to replace QBGLVideoView with the newest QBRTCRemoteVideoView you should create UIView with QBRTCRemoteVideoView on it to show video views with streams which you have received from your opponents, then use the following code:

- (void)session:(QBRTCSession *)session receivedRemoteVideoTrack:(QBRTCVideoTrack *)videoTrack fromUser:(NSNumber *)userID {
    // we suppose you have created UIView and set it's class to QBRTCRemoteVideoView class
    // also we suggest you to set view mode to UIViewContentModeScaleAspectFit or
    // UIViewContentModeScaleAspectFill
    [self.opponentVideoView setVideoTrack:videoTrack];
}

to replace local video track you need to do the following in your class(for example we name it as CallController): declare
@interface CallController()
@property (weak, nonatomic) IBOutlet UIView *localVideoView; // your video view to render local camera video stream
@property (strong, nonatomic) QBRTCCameraCapture *videoCapture;
@end
then in viewDidLoad call the following
QBRTCVideoFormat *videoFormat = [[QBRTCVideoFormat alloc] init];
videoFormat.frameRate = 30;
videoFormat.pixelFormat = QBRTCPixelFormat420f;
videoFormat.width = 640;
videoFormat.height = 480;
// QBRTCCameraCapture class used to capture frames using AVFoundation APIs
self.videoCapture = [[QBRTCCameraCapture alloc] initWithVideoFormat:videoFormat position:AVCaptureDevicePositionFront];
// or AVCaptureDevicePositionBack, front or back camera
self.videoCapture.previewLayer.frame = self.localVideoView.bounds;
[self.videoCapture startSession];
[self.localVideoView.layer insertSublayer:self.videoCapture.previewLayer atIndex:0];
self.session.localMediaStream.videoTrack.videoCapture = self.videoCapture;
localVideoView above is your previous QBGLVideoView you used to show your local video track, simply remove QBGLVideoView class from UIView in Xcode inspector
To enable/disable audio/video use
session.audioEnabled => self.session.localMediaStream.audioTrack.enabled
session.videoEnabled => self.session.localMediaStream.videoTrack.enabled
skipBlackFrames property is now managed automatically by SDK

To switch whether to use back or front camera refer to: http://quickblox.com/developers/Sample-webrtc-ios#Switch_camera

Also remember to subscribe your webrtc classes to QBRTCClient notifications [QBRTCClient.instance addDelegate:self];

[QBRTCClient.instance addDelegate:self];

and please  sync all methods in @protocol QBRTCClientDelegate <NSObject>

**Comment by itsaboutcode** [comment]
Thanks @Pro100Andrey 
I believe the correct method is

    session: didReceiveRemoteVideoTrack: fromUser

Plus I am getting this strange error.

<img width="1188" alt="screen shot 2015-12-22 at 12 51 04 pm" src="https://cloud.githubusercontent.com/assets/204423/11950495/93704888-a8aa-11e5-89b5-dd8f1223283e.png">

**Comment by Pro100Andrey** [comment]
Hi @itsaboutcode !
Please add:
```objective-c
#if TARGET_OS_IPHONE
#import <UIKit/UIKit.h>
#endif 
```
into QBRTCVideoRenderer.h header.
we update this in next release

**Comment by itsaboutcode** [comment]
@Pro100Andrey Thanks.

Now we are getting following errors (I am getting same error with a new project too)
```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_GLKView", referenced from:
      objc-class-ref in QuickbloxWebRTC(libjingle_peerconnection_objc.RTCEAGLVideoView.o)
  "_VTCompressionSessionCreate", referenced from:
      webrtc::H264VideoToolboxEncoder::ResetCompressionSession() in QuickbloxWebRTC(webrtc_h264_video_toolbox.h264_video_toolbox_encoder.o)
  "_VTCompressionSessionEncodeFrame", referenced from:
      webrtc::H264VideoToolboxEncoder::Encode(webrtc::VideoFrame const&, webrtc::CodecSpecificInfo const*, std::__1::vector<webrtc::FrameType, std::__1::allocator<webrtc::FrameType> > const*) in QuickbloxWebRTC(webrtc_h264_video_toolbox.h264_video_toolbox_encoder.o)
  "_VTCompressionSessionGetPixelBufferPool", referenced from:
      webrtc::H264VideoToolboxEncoder::Encode(webrtc::VideoFrame const&, webrtc::CodecSpecificInfo const*, std::__1::vector<webrtc::FrameType, std::__1::allocator<webrtc::FrameType> > const*) in QuickbloxWebRTC(webrtc_h264_video_toolbox.h264_video_toolbox_encoder.o)
  "_VTCompressionSessionInvalidate", referenced from:
      webrtc::H264VideoToolboxEncoder::DestroyCompressionSession() in QuickbloxWebRTC(webrtc_h264_video_toolbox.h264_video_toolbox_encoder.o)
  "_VTDecompressionSessionCreate", referenced from:
      webrtc::H264VideoToolboxDecoder::ResetDecompressionSession() in QuickbloxWebRTC(webrtc_h264_video_toolbox.h264_video_toolbox_decoder.o)
  "_VTDecompressionSessionDecodeFrame", referenced from:
      webrtc::H264VideoToolboxDecoder::Decode(webrtc::EncodedImage const&, bool, webrtc::RTPFragmentationHeader const*, webrtc::CodecSpecificInfo const*, long long) in QuickbloxWebRTC(webrtc_h264_video_toolbox.h264_video_toolbox_decoder.o)
  "_VTDecompressionSessionInvalidate", referenced from:
      webrtc::H264VideoToolboxDecoder::~H264VideoToolboxDecoder() in QuickbloxWebRTC(webrtc_h264_video_toolbox.h264_video_toolbox_decoder.o)
      webrtc::H264VideoToolboxDecoder::DestroyDecompressionSession() in QuickbloxWebRTC(webrtc_h264_video_toolbox.h264_video_toolbox_decoder.o)
      webrtc::H264VideoToolboxDecoder::ResetDecompressionSession() in QuickbloxWebRTC(webrtc_h264_video_toolbox.h264_video_toolbox_decoder.o)
  "_VTSessionSetProperty", referenced from:
      webrtc::H264VideoToolboxDecoder::ResetDecompressionSession() in QuickbloxWebRTC(webrtc_h264_video_toolbox.h264_video_toolbox_decoder.o)
      webrtc::H264VideoToolboxDecoder::ConfigureDecompressionSession() in QuickbloxWebRTC(webrtc_h264_video_toolbox.h264_video_toolbox_decoder.o)
      internal::SetVTSessionProperty(void const*, __CFString const*, int) in QuickbloxWebRTC(webrtc_h264_video_toolbox.h264_video_toolbox_encoder.o)
      internal::SetVTSessionProperty(void const*, __CFString const*, bool) in QuickbloxWebRTC(webrtc_h264_video_toolbox.h264_video_toolbox_encoder.o)
      internal::SetVTSessionProperty(void const*, __CFString const*, __CFString const*) in QuickbloxWebRTC(webrtc_h264_video_toolbox.h264_video_toolbox_encoder.o)
  "_kVTCompressionPropertyKey_AllowFrameReordering", referenced from:
      webrtc::H264VideoToolboxEncoder::ConfigureCompressionSession() in QuickbloxWebRTC(webrtc_h264_video_toolbox.h264_video_toolbox_encoder.o)
  "_kVTCompressionPropertyKey_AverageBitRate", referenced from:
      webrtc::H264VideoToolboxEncoder::SetRates(unsigned int, unsigned int) in QuickbloxWebRTC(webrtc_h264_video_toolbox.h264_video_toolbox_encoder.o)
      webrtc::H264VideoToolboxEncoder::ConfigureCompressionSession() in QuickbloxWebRTC(webrtc_h264_video_toolbox.h264_video_toolbox_encoder.o)
  "_kVTCompressionPropertyKey_ProfileLevel", referenced from:
      webrtc::H264VideoToolboxEncoder::ConfigureCompressionSession() in QuickbloxWebRTC(webrtc_h264_video_toolbox.h264_video_toolbox_encoder.o)
  "_kVTCompressionPropertyKey_RealTime", referenced from:
      webrtc::H264VideoToolboxEncoder::ConfigureCompressionSession() in QuickbloxWebRTC(webrtc_h264_video_toolbox.h264_video_toolbox_encoder.o)
  "_kVTDecompressionPropertyKey_RealTime", referenced from:
      webrtc::H264VideoToolboxDecoder::ResetDecompressionSession() in QuickbloxWebRTC(webrtc_h264_video_toolbox.h264_video_toolbox_decoder.o)
      webrtc::H264VideoToolboxDecoder::ConfigureDecompressionSession() in QuickbloxWebRTC(webrtc_h264_video_toolbox.h264_video_toolbox_decoder.o)
  "_kVTEncodeFrameOptionKey_ForceKeyFrame", referenced from:
      webrtc::H264VideoToolboxEncoder::Encode(webrtc::VideoFrame const&, webrtc::CodecSpecificInfo const*, std::__1::vector<webrtc::FrameType, std::__1::allocator<webrtc::FrameType> > const*) in QuickbloxWebRTC(webrtc_h264_video_toolbox.h264_video_toolbox_encoder.o)
  "_kVTProfileLevel_H264_Baseline_AutoLevel", referenced from:
      webrtc::H264VideoToolboxEncoder::ConfigureCompressionSession() in QuickbloxWebRTC(webrtc_h264_video_toolbox.h264_video_toolbox_encoder.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)```

<img width="1177" alt="screen shot 2015-12-22 at 4 39 52 pm" src="https://cloud.githubusercontent.com/assets/204423/11954482/98410760-a8ca-11e5-8b13-a45e67bce02f.png">

**Comment by itsaboutcode** [comment]
<img width="1177" alt="screen shot 2015-12-22 at 4 39 52 pm" src="https://cloud.githubusercontent.com/assets/204423/11954482/98410760-a8ca-11e5-8b13-a45e67bce02f.png">

**Comment by Pro100Andrey** [comment]
@itsaboutcode Please check http://quickblox.com/developers/Sample-webrtc-ios#Step_3:_Link_Binary_With_Library_Frameworks

and add VideoToolbox.framework ;)

**Comment by itsaboutcode** [comment]
@Pro100Andrey - I am using cocoapods, so I believe it should have included all of these things itself?

**Comment by Pro100Andrey** [comment]
@itsaboutcode  A good idea!! we added it, Thanks!

**Comment by Pro100Andrey** [comment]
@itsaboutcode  Any questions ?

**Comment by itsaboutcode** [comment]
@Pro100Andrey - Nopes. Please update your docs. Thanks!!!

**Comment by rathod24** [comment]
![screen shot 2015-12-24 at 2 44 32 pm](https://cloud.githubusercontent.com/assets/16424775/11992509/eb71fcfe-aa4c-11e5-89a9-21ff5714128e.png)

@Pro100Andrey - I'm getting error from QBRTCFrameConverter.h on method named prepareForSourceDimensions on project build

**Comment by Raikerian** [comment]
@rathod24 please create separate issue.
