### ISSUE TITLE
Chatting decode

### ISSUE THREAD

**Issue by buithuyen** [QuickBlox/quickblox-ios-sdk#272]
I type `I'm` and UI appear `I&apos;m`

**Comment by Raikerian** [comment]
Hi,

Please provide us more information on how to reproduce this. Just tested it in our samples and everything working as intended.

**Comment by coredream** [comment]
This might not be the same issue, but I was wondering the same thing when integrating the SDK.  What I found was that in QMChatService.m `sendMessage:`, it HTML encodes the message:
```
message.text = [message.text gtm_stringByEscapingForHTML];
```

When I tried to display the message in my app using `.text` (for example in a UITableViewCell), it shows up with HTML encoding (e.g., `I&apos;m here`):
```
QBChatMessage* message = ...
cell.body.text = message.text;
```
So I believe the correct way is to use `encodedText`, defined in category QBChatAbstractMessage+TextEncoding.h which decodes the HTML entities:
```
text = [self.text gtm_stringByUnescapingFromHTML];
```
And then it shows up correctly in my cell (e.g., `I'm here`):
```
QBChatMessage* message = ...
cell.body.text = message.encodedText;
```
I think this could be documented better, and perhaps the name should be `decodedText`, but it looks like this is what the sample app is doing.

**Comment by Raikerian** [comment]
Hi,

Yeah, this is our custom category to encode/decode text in a correct way. It is implemented in our [QMServices](https://github.com/QuickBlox/q-municate-services-ios'q-municate-services-ios') project, so you can easily integrate it in your own project. It wasn't done by default in SDK because some people may not need this.

You are right about documenting this, we will consider doing it in the near updates :)

**Comment by buithuyen** [comment]
Thank you guys, It work for me!
