### ISSUE TITLE
User is logged in but can't connect to chat

### ISSUE THREAD

**Issue by kevb10** [QuickBlox/quickblox-ios-sdk#305]
Hi,
My user is connected but the chat is showing the following error:

`[ChatService] Did not authenticate, error: <failure xmlns="urn:ietf:params:xml:ns:xmpp-sasl"><not-authorized></not-authorized><text lang="en">Password not verified</text></failure>`

Here is a gist of my login function
https://gist.github.com/kevb10/f2c6fc18372bcdc8719d

I feel like it's a simple thing that I'm missing.

**Comment by tonchis** [comment]
Hi @kevb10. I'm not a part of the @QuickBlox-team, just another user, but I've experienced this myself.

Before calling `QBChat.connectWithUser` you need to set the `password` attribute to the `user` object returned by the first `QBRequest.logInWithUserLogin`, just like they do [here](http://quickblox.com/developers/SimpleSample-chat_users-ios#Connect_to_Chat)

Try something like
```objc
[QBRequest logInWithUserLogin:username password:password successBlock:^(QBResponse *response, QBUUser *user) {
        if (user) {
            user.password = password;
            __typeof(self) strongSelf = weakSelf;
            [[QBChat instance] connectWithUser:user completion:^(NSError * _Nullable error) {
```

This code above might not be accurate (I'm doing Swift, not ObjC), but you get the idea.

I'm guessing the reason why the `QBUUser` object returned doesn't have the password set is because of security concerns.

Let me know if it works :)
Good luck!

**Comment by kevb10** [comment]
Not much luck. It kinda just gets stuck now. Here is what's being spitted out in the debugger:

`2016-02-24 10:07:44.178 Vice Versa[46573:8691060] [Core] Set default chat endpoint for QBConnectionZoneTypeAutomatic`
`2016-02-24 10:07:44.182 Vice Versa[46573:8691060] [ChatService] Connecting to Chat, host: chat.quickblox.com, user JID: 8334346-33477@chat.quickblox.com/8BEFA367-20AC-42B1-8525-735844DC1083`
`2016-02-24 10:10:38.377 Vice Versa[46573:8692113] [ChatService] Did disconnect`

**Comment by tonchis** [comment]
@kevb10 I believe the connection works fine, because you're getting back a `JID` (Jabber ID). Also, this output is the same as mine:

```
[ChatService] Connecting to Chat, host: chat.quickblox.com, user JID: 9050036-35265@chat.quickblox.com/F9A76ED2-CC6D-426A-B2C5-4FDFAAC4A96F
```

Place a breakpoint inside the `completion` block at the `connectWithUser` method to get debug this a bit further.

Also check if you need to upgrade the QB framework. Latest version is 2.6.6

**Comment by Raikerian** [comment]
Hi kevb10,

As @tonchis you need a valid password in QBUUser instance in order to login in chat using QBChat methods. Please note, that QBRequest never returns user password in completion block, you need to set it by yourself.
If that is not helpful please provide us full log from app start till error, that you are getting.

**Comment by kevb10** [comment]
Yup! The update did it.(Previously 2.6.5)
I appreciate it @tonchis  :+1:

**Comment by optimumbrew** [comment]
hi @**tonchis**  QBChat connect chat method are

QBChat.instance.connect(with: user, completion: {(_ error: Error?) -> Void in

                })

**Comment by optimumbrew** [comment]
hi 

QBChat.instance.connect(with: user, completion: {(_ error: Error?) -> Void in
                    
  })
