### ISSUE TITLE
CurrentUser == nil on physical device

### ISSUE THREAD

**Issue by rvilches** [QuickBlox/quickblox-ios-sdk#384]
Hi guys.
Im getting nil on QBSession.currentSession().currentUser if I run my code on my iphone after a couple of hours (like more 6 than hours) of the application been inactive. I am asking because in the simulator everything run just fine , I can stop the app , close xcode, the simulator and in the next day run it and it does the "auto login" but not in the Devices. 

Here is the code that I am using to manage the login:

```swift
if QBSession.currentSession().currentUser != nil
        {
            
            if QBSession.currentSession().sessionExpirationDate!.compare(NSDate()) ==       NSComparisonResult.OrderedAscending
            {
                self.updateSessionTokenWithUser(QBSession.currentSession().currentUser!)
            }
            else
            {
               self.connectToQBChat()
            }
        }
        else
        {
            //USER WAS NIL
            self.passToLoginView(true)
        }

/*--------------------------------------------------------------------------------------------*/
// Do a random request to update the session token if the user is not nil
but the session Date has expired

func updateSessionTokenWithUser(user:QBUUser)
    {
        
       QBRequest.usersWithIDs([String(user.ID)], page: nil, successBlock:
        {(response:QBResponse, page: QBGeneralResponsePage?, Users:[QBUUser]?)-> Void in
        
            self.updateLocalUserInfo(QBSession.currentSession().currentUser!)
            self.connectToQBChat()
            
        },
        errorBlock:
            {(error:QBResponse?)-> Void in
                self.passToLoginView(true)
                print(error!.description)
            })
        
    }
```

**Comment by VitaliyGuru** [comment]
Hi @rvilches ,
Could you please provide us your version of SDK?

**Comment by rvilches** [comment]
Yes , Im using the last one the 2.7

**Comment by VitaliyGuru** [comment]
@rvilches,
Situation, when currentUser == nil is uncommon for us.
So it's difficult to answer to your question without logs. Could you please attache them?

**Comment by rvilches** [comment]
@VitaliyGuru 

I dont know if this s helpful but her:

I call this:

print("HERE IS THE SESSION DETAILS: \(QBSession.currentSession().sessionDetails)")
print("HERE IS THE SESSION CURRENT USER: \(QBSession.currentSession().currentUser)")

and the logs are: 
HERE IS THE SESSION DETAILS: Optional(
  [QBASession]:
  ID:52927
  created at:2016-04-04 23:21:43 +0000
  updated at:2016-04-04 23:21:43 +0000
  token:14d9a5800885a1f0e7a67d2044f8b3b4cc2b2897
  applicationID:3....
  userID:10824123
  deviceID:0
  timestamp:1459812103
  nonce:241)
HERE IS THE SESSION CURRENT USER: nil

**Comment by iSevenDays** [comment]
Hi @rvilches 
Have you checked this http://quickblox.com/developers/IOS#Initialize_framework ?

QBSession.currentSession().currentUser will be nil because after startSessionWithDetails you should manage session by yourself.

You should call startSessionWithDetails: only in updateSessionBlock

After one failed request to a server with next request updateSessionBlock will be called automatically, in that block you should make synchronous request(NOT asynchronous) to your custom server to get token, the you should call startSessionWithDetails:

Thanks

**Comment by rvilches** [comment]
Hi @iSevenDays 
Yes I did read that , and I know I asked for the "startSessionWithDetails" method a couple of days ago, but that was trying to solve this problem. 
I am not using startSessionWithDetails in this code since I am using the last SDK version that ,as I understand , automatically manage sessions right?
The "updateSessionTokenWithUser" method that is in my code is one made by myself, it just do a random call to update de token since the SDK documentation says that do any request will automatically update the token if it is expired

**Comment by iSevenDays** [comment]
Hi @rvilches 

After a call to startSessionWithDetails: or startSessionWithDetails: updateSessionBlock: SDK disables auto create session feature, so you should manage the session by yourself

**Comment by rvilches** [comment]
Understood , but is that method called automatically ? Because I have not called it anywhere in this project.
And that is the weird thing,  in the simulator can pass days and the QBSession.currentSession().currentUser never gets nil unless I logout. I just have to update the token and I am good to go. But in the physical devices it does turn nil after a couple of hours. I could say, after 6-7 hours.

I am not using startSessionWithDetails: or startSessionWithDetails: updateSessionBlock: in this project

**Comment by iSevenDays** [comment]
Hi @rvilches 

You don't have to manage session details by yourself if you use auto create session which is enabled by default
The code below is unneeded
```
            {
                self.updateSessionTokenWithUser(QBSession.currentSession().currentUser!)
            }
```

Also you don't have to update the token by yourself because SDK do it for you automatically.

If you access and modify session properties then we can not guarantee that currentUser will not be nil because auto create session will be disabled.

**Comment by rvilches** [comment]
Hi @iSevenDays 
The problem is that if I dont do that then I am not able to connect to the chat with the existent token as password. I got this message because the token is old: 

JID: 10824123-34835@chat.quickblox.com/C999A925-1086-4090-9601-790759CA00DE
2016-04-08 11:04:24.018 meetMe[7214:8456090] [ChatService] Stream did connect, supportsStartTLS: 1
2016-04-08 11:04:24.019 meetMe[7214:8456090] [ChatService] Trying TLS...
2016-04-08 11:04:24.511 meetMe[7214:8456020] [ChatService] Stream isSecure: YES
2016-04-08 11:04:24.645 meetMe[7214:8456029] [ChatService] Stream did connect, supportsStartTLS: 0
2016-04-08 11:04:24.715 meetMe[7214:8456029] [ChatService] Did not authenticate, error: <failure xmlns="urn:ietf:params:xml:ns:xmpp-sasl"><not-authorized/><text lang="en">Password not verified</text></failure>
2016-04-08 11:04:24.717 meetMe[7214:8456090] [ChatService] Did disconnect


But if I do the request I force the token to refresh and then I can connect to chat without problems. I do that because in the documentation says that the token will automatically refreshed after any request.

**Comment by Raikerian** [comment]
Hi @rvilches 

As I can see, your problem is that you need to update a token **before** chat connect, cause you cannot guarantee that it is valid at the time you are trying to perform that. There is a possible solution for you. Every QBRequest method we have in SDK is checking session token to be valid before perform any operation. There is for sure some QBRequest methods you are performing after app become active. You can check token for expiration, and if it is expired, wait for any of QBRequest's completion block, after that token value of current session will be valid again.
The second solution for you is to manage current user by yourself, in some kind of singleton class :)

**Comment by rvilches** [comment]
Yes that's what I am doing. Thanks guy for your sugestions.

**Comment by Raikerian** [comment]
@rvilches If you are still having any other questions, feel free to let us know by creating a separate issue.
