### ISSUE TITLE
Can't update exist user to CoreData

### ISSUE THREAD

**Issue by nikeboi89** [QuickBlox/quickblox-ios-sdk#409]
Hi,

I wanted to update user to CoreData. I fetched user from server and then called [QMUsersCache.instance insertOrUpdateUsers:@[user]] but it couldn't update. I changed full name of existed user but when it compared with user from cache, it recognised the two users is similar and didn't add updated user to toupdate array.

Can you check?

Here is the info of users:

Cached User:
[QBUUser]:
  ID:6174
  created at:2016-02-18 04:23:03 +0000
  updated at:2016-04-25 08:55:00 +0000
  externalUserID:6376
  blobID:0
  facebookID:(null)
  twitterID:(null)
  twitterDigitsID:(null)
  **full name:Hoang Nguyen**
  email:hoang@ee.com
  login:6376
  phone:1111
  tags:(null)
  lastRequestAt:2016-04-25 09:05:59 +0000
  website:(null)

Updated User from server:
[QBUUser]:
  ID:6174
  created at:2016-02-18 04:23:03 +0000
  updated at:2016-04-25 09:10:46 +0000
  externalUserID:6376
  blobID:0
  facebookID:(null)
  twitterID:(null)
  twitterDigitsID:(null)
**full name:Nguyen Ngoc Hoang**
  email:hoang@ee.com
  login:6376
  phone:123456
  tags:(null)
  lastRequestAt:2016-04-25 09:13:02 +0000
  website:(null)

I'm using QMService 0.4

**Comment by Raikerian** [comment]
Hi @nikeboi89 

We will update QMUsersService logic with possibility of update users in a near future releases. Right now there is a possible way for you. In QMChatCache class, 'insertOrUpdateUsers:' method there is an equality check: https://github.com/QuickBlox/q-municate-services-ios/blob/master/QMUsersCache/QMUsersCache/QMUsersCache.m#L76
isEqual method returns always YES if IDs of both QBUUser instances are same. In order to force user update, you also need to add a check for equality of updatedAt field here.

**Comment by nikeboi89** [comment]
👍  Ok I'll try! Thanks
