### ISSUE TITLE
How to customised or else use my own nib for tool bar in ChatViewController using Quickblox?

### ISSUE THREAD

**Issue by WillsAtIOS** [QuickBlox/quickblox-ios-sdk#468]
I want to use a custom tool bar for my chat view controller instead of existing tool bar available in sample-chat-IOS app.

And I don't want to disturb exiting QMToolbarContentView.nib and QMToolbarContentView.h and QMToolbarContentView.m files. Below Image 1 is the existing one. and Image 2 is what I want.

So which is the best to load my own tool bar nib. Is it possible or I should modify the existing one ?

And I found one method but don't know weather this will work ?

Please go through this stack over flow link to see the images and complete question.

[http://stackoverflow.com/questions/37215391/how-to-customised-or-else-use-my-own-nib-for-tool-bar-in-chatviewcontroller-usin]

Environment details
iOS version, Quickblox iOS SDK version, QMChatViewController version

**Comment by Raikerian** [comment]
Hi,

There is a property in QMChatViewController.h file representing toolbar: https://github.com/QuickBlox/QMChatViewController-ios/blob/master/QMChatViewController/QMChatViewController.h#L46

The easiest way for you will be to modify the existing xib file and class interface to your like. In order to do it install QMChatViewController as development pod or fork from our QMChatViewController repository.

**Comment by Raikerian** [comment]
If you are still having any other troubles, please let us know by creating a separate issue.
