### ISSUE TITLE
Share location

### ISSUE THREAD

**Issue by mallikaD** [QuickBlox/quickblox-ios-sdk#499]
Is it possible to share location like in whatsup app? Is it possible by using quickblox sdk?If you have any code samples for this please help me out.

**Comment by Raikerian** [comment]
Hi @mallikaD 

Yes it is possible. Please see our [location code sample](http://quickblox.com/developers/SimpleSample-location_users-ios).

**Comment by mallikaD** [comment]
Means i want to share the location in chat dialog like image sharing.Is it possible?

**Comment by Raikerian** [comment]
Yes, you can share geodata in custom parameters of both message or chat dialog.

**Comment by Kiran-Patel** [comment]
The one which was referred ago in this thread [location code sample](http://quickblox.com/developers/SimpleSample-location_users-ios) has been deprecated and is no longer maintained now. Instead  they suggest that in order to achieve similar functionality, we should use the [Custom Objects module](https://quickblox.com/developers/Custom_Objects).

**Does any one have any hint with new [Custom Objects module](https://quickblox.com/developers/Custom_Objects) feature that, how we can share user's current location(not live location) like WhatsApp using QuickBlox?**
