### ISSUE TITLE
Please help me to show online offline users in swift

### ISSUE THREAD

**Issue by vibha22** [QuickBlox/quickblox-ios-sdk#593]
I used this but not working 

let nowTime = user.updatedAt!
 let interval = NSDate().timeIntervalSinceDate(nowTime)
            
            if(interval > 5*60)
            {
               print("offline")
            }else
            {
                print("online")
            }

**Comment by Raikerian** [comment]
Hi,

The approach you have chosen requires you to update QBUUser instance from server, in order to do it, you need to fetch this user by ID using QBRequest method.

There is more easy way to know if user online. Our QBChat has contactList. Every contact list item has online property, which is updated once user status has been changed.

**Comment by Raikerian** [comment]
@vibha22 
If you are still having any other troubles, please let us know by creating a separate issue.
