### ISSUE TITLE
sample chat demo crash

### ISSUE THREAD

**Issue by mohsinalimat** [QuickBlox/quickblox-ios-sdk#617]
Hello,

sample chat demo crash on launch....

**Comment by Pro100Andrey** [comment]
Hi @mohsinalimat, please provide information about:
+ Crash stack trace from `Xcode` console
+ `Xcode` version

**Comment by mohsinalimat** [comment]
Xcode version - 7.3.1

**Comment by Pro100Andrey** [comment]
[Dublicate](https://github.com/QuickBlox/quickblox-ios-sdk/issues/610)

**Comment by Raikerian** [comment]
Hi,

We were able to fix that and the fresh updated Quickblox iOS SDK build is now available in master branch. Check out our latest commit in master.
The problem was, that the binary was built under the macOS sierra, which for some reason does not want to work with Xcode 7 simulators. Updated binary was built under the OSX 10.11.
