### ISSUE TITLE
App is crashing after launch in simulate

### ISSUE THREAD

**Issue by smadupu** [QuickBlox/quickblox-ios-sdk#618]
**Environment details**
*iOS version:9.3, Quickblox iOS SDK version:2.8.0.1*

**Did this work before?**
Yes

**Expected behavior**
App should launch and work with out crash after install into simulator.

**Actual behavior**
App is crashing immediately after launch.

**Logs**
*Attach full logs that will describe your problem (please, use github [gist](https://gist.github.com
![screen shot 2016-10-06 at 6 16 16 pm](https://cloud.githubusercontent.com/assets/20111587/19181961/eb244292-8c8d-11e6-858e-282dbf185d00.png)

with error **Message from debugger: Terminated due to code signing error**
/))*

**Comment by Pro100Andrey** [comment]
Hi @smadupu, please provide `xсode` version

**Comment by smadupu** [comment]
Xcode version: 7.3

**Comment by Pro100Andrey** [comment]
[Dublicate](https://github.com/QuickBlox/quickblox-ios-sdk/issues/610)

**Comment by Pro100Andrey** [comment]
[Dublicate](https://github.com/QuickBlox/quickblox-ios-sdk/issues/610)

**Comment by Raikerian** [comment]
Hi,

We were able to fix that and the fresh updated Quickblox iOS SDK build is now available in master branch. Check out our latest commit in master.
The problem was, that the binary was built under the macOS sierra, which for some reason does not want to work with Xcode 7 simulators. Updated binary was built under the OSX 10.11.
