### ISSUE TITLE
connectWithUser completion block never called

### ISSUE THREAD

**Issue by mpc20001** [QuickBlox/quickblox-ios-sdk#667]
*Help avoid duplicate issue reports, check [existing issues](https://github.com/QuickBlox/quickblox-ios-sdk/issues)*
 
**Environment details**
*iOS version, Quickblox iOS SDK version, QuickbloxWebRTC SDK version (optional)*
ios 10,  Quickblox iOS SDK 2.9

**Did this work before?**
Yes

**Expected behavior**
connectWithUser connects to chat and completion block is called setting the QBChat.instance() isConnected to true

**Actual behavior**
connectWithUser connects to chat (I can see via logs) but the completion block is never called.
QBChat.instance().isConnected is still set to false. When I try and send  a message a get an error about not being connected but when I try to reconnect it says I can't connect because I am already connected. I had one test case where after 5 minutes the completion block was called and then I was allowed to send messages. 
**Logs**
*Attach full logs that will describe your problem (please, use github [gist](https://gist.github.com/))*
First I get a message - [ChatService] Stream isSecure: YES 
but when I send a message i get 
com.quickblox.chat Code=-1002 
NSLocalizedRecoverySuggestion=You are not connected to chat.

then when i try to reconnect i get 

Connection error: Error Domain=XMPPStreamErrorDomain Code=1 "Attempting to connect while already connected or connecting." UserInfo={NSLocalizedDescription=Attempting to connect while already connected or connecting.}

**Steps to reproduce the behavior**

**Any others comments?**

**Comment by Raikerian** [comment]
Hi @mpc20001 

Please be notified, that there is a critical issue on Shared server (https://admin.quickblox.com). 

Our tech operations team noticed unknown chat server degradation due to immediate spike of usage or attack. 

Team is on this urgent issue and working hard to localize it. 

As soon there is any progress we will provide an update on the blog 
http://quickblox.com/blog/shared-instance-chat-performance-degradation/ 
and you can see update on Shared instance  status page  https://status.quickblox.com/instance/prod

Thank you for understanding and patience!

**Comment by mpc20001** [comment]
Oh good! I thought it was code related.

**Comment by Raikerian** [comment]
@mpc20001 please check this now. Our server did have some problems last week, should be fixed now.

**Comment by Raikerian** [comment]
Let us know if its still not working. Should be fixed by now on.

**Comment by astanton** [comment]
I am getting this same issue right now.  It just hangs on the connecting block and is never called.  If I step over it, isConnected is still false and isConnecting stays true.

**Comment by mpc20001** [comment]
At the time it was related to the servers getting attacked.
