### ISSUE TITLE
QBResponsePage

### ISSUE THREAD

**Issue by gask** [QuickBlox/quickblox-ios-sdk#67]
Hey there, I think I'm missing something about the paging system.
I'm trying to get all the dialogs with the method from QBRequest "dialogsForPage:extendedRequest:sucessBlock:errorBlock". When I try to access the "page" variable (a QBResponsePage instance) from the successBlock, it doesn't say to me how many pages I still have to download. I'm missing a "totalEntries" property, as present in the class QBGeneralResponsePage.

I mean, how am I supposed to know the total number of dialogs I have on the server without receiving it from the callback? Please, this is very important for my application...

Thanks in advance
Gio.

**Comment by soulfly** [comment]
QBResponsePage doesn't work for Chat and CustomObjects models because it's another storage used internally. 

For now the only one way to get all dialogs is to request them by changing the 'offset' parameter and when it will return 0 then it means that there is no more dialogs.

Incoming release 2.3 will contain next methods:
    [QBRequest countDialogsWithExtendedRequest:successBlock:errorBlock:]
    [QBRequest countMessagesWithExtendedRequest:successBlock:errorBlock:]
