### ISSUE TITLE
JS SDK: Could not send custom data while audio/video call to IOS SDK

### ISSUE THREAD

**Issue by olimjon** [QuickBlox/quickblox-ios-sdk#697]
**Environment details**
*(Operating system, browser information, SDK version)*

1 Side:  QuickBlox JavaScript SDK - v2.1.2 - 2016-05-16  

2 Side: iOS version: 9.3.2
Quickblox iOS SDK version: 2.7.6
QuickbloxWebRTC SDK version: 2.2
Language: Objective-C
XCode version: 8.1

 
**Did this work before?**
No 

**Expected behavior**
We want send extra data while call. We are using session object's call method. There is a problem to get this data from IOS SDK. 

**Actual behavior**
we are sending js Object like this: 

this.currentSession.call({compact_data:compact_data}, function (error) {}) 

I can get this object using JS SDK. But there is some trouble with getting this data from IOS SDK. it gets nil; 

**Steps to reproduce the behavior**
pass js object while calling to IOS device. monitor custom data from IOS

**Comment by olimjon** [comment]
Also asked here: https://github.com/QuickBlox/quickblox-javascript-sdk/issues/185

**Comment by Pro100Andrey** [comment]
@olimjon Please provide logs

**Comment by olimjon** [comment]
logs of web app or IOS app?

**Comment by Pro100Andrey** [comment]
@olimjon for enable logs use:
```objc
[QBSettings setLogLevel:QBLogLevelDebug];
[QBSettings enableXMPPLogging];
```

**Comment by Pro100Andrey** [comment]
@olimjon 
> Q: logs of web app or IOS app?
A: iOS

**Comment by Shamsiddin** [comment]
Hi @Pro100Andrey.

Here's what we've received on iOS side ([see attachment](https://github.com/QuickBlox/quickblox-ios-sdk/files/641302/called_received_accepted_talked_hungup.txt)) with loggings enabled as you said.
We've checked through `XML/XMPP` logs and found our `userInfo` data in `XML` format.
You can find this `userInfo` data under `extraParams` field.
We are sure it is received but not in `userInfo` dictionary on 

`- (void)didReceiveNewSession:(QBRTCSession *)session userInfo:(NSDictionary *)userInfo;`

method.

`userInfo` is still nil.

Is it fixed in the latest version? If yes we'll consider on updating of iOS SDK, or give us suggestion what to do.

Thanks.

**Comment by Pro100Andrey** [comment]
hi @olimjon, need add userInfo tags, for example:

`<userInfo> {compact_data:compact_data}  </userInfo>`

**Comment by Pro100Andrey** [comment]
@olimjon 

```xml
<message 
  xmlns="jabber:client" to="10166104-31216@chat.quickblox.com" 
  type="headline" id="584934536214f45b2f00000f"
  from="11384382-31216@chat.quickblox.com/1571722472-quickblox-550581">
    <extraParams xmlns="jabber:client">
      //Missing user info
      <userInfo>
        <contact_type>1</contact_type>
        <first_name>Katta</first_name>
        <last_name>Ayiq</last_name>
        <qb_id>11384382</qb_id>
        <contact_id>31</contact_id>
        ...
      </userInfo>
```

please check [signalling spec]( http://quickblox.com/developers/VideoChat#Signaling_v1.0)

**Comment by Shamsiddin** [comment]
Hi @Pro100Andrey we are at the same team with @olimjon .

Can you explain how to access that XML from iOS sdk? Where we have to add userInfo tags?

**Comment by Pro100Andrey** [comment]
JS side

**Comment by Shamsiddin** [comment]
Can you please clarify? Do you need JS side logs?

**Comment by Shamsiddin** [comment]
Thanks, it worked.
