### ISSUE TITLE
How to restrict previous messages in group chat for the user added in the middle.

### ISSUE THREAD

**Issue by Narendrastellent** [QuickBlox/quickblox-ios-sdk#705]
When i  add a user in a particular situation it display early messages for that user. how can i remove previous messages in a group and also display only after added messages displaying for that user.
can you  please help me .

**Comment by Raikerian** [comment]
Hi,

In order to do so, you need to fetch messages for that specific dialog only from date use was joined. Use our [Custom objects](http://quickblox.com/developers/SimpleSample-customObjects-ios) module in order to save and operate with that date.

Right now thats an expected backend behaviour for user to see all messages in dialog.

**Comment by Narendrastellent** [comment]
Can you please provide sample and also how to use the custom objects.

**Comment by Raikerian** [comment]
Yes, we have custom objects sample in current repository and here is detailed guide on it: http://quickblox.com/developers/SimpleSample-customObjects-ios

**Comment by Narendrastellent** [comment]
Ok thank you.

**Comment by Raikerian** [comment]
Let us know if you will have any other issues by creating a separate one. Closing this as resolved.
