### ISSUE TITLE
isLoggedin (v2.0.10) no longer working? 

### ISSUE THREAD

**Issue by remkohdev** [QuickBlox/quickblox-ios-sdk#707]
I know there has been a new syntax 'isConnected' but since there has not been a major version upgrade to v3 older methods should still be supported and the server code should be backward compatible. This is causing major issues for our application disabling the complete messaging feature of a social production app.

**Comment by Raikerian** [comment]
Hi,

> since there has not been a major version upgrade to v3 older methods should still be supported

We are are supporting old methods upon subversions instead of major versions, that means that methods from 2.1 can be deprecated in 2.2, but removed in 2.3. But it will never happen in sub versions, such as 2.2.1 etc. We are more focused on such philosophy, than make major (2.0, 3.0 etc) version too frequently (you can look all release dates in our changeling here: http://quickblox.com/developers/IOS#Framework_changelog ). As our subversions usually have major changes, while minor versions (like 2.2.1) have really small, it is not possible to keep very old methods in framework all along.

To answer your issue, isConnected is just the same as isLoggedIn previously, only changes is naming. 

> This is causing major issues for our application disabling the complete messaging feature of a social production app.

If you are having any issues in our new framework, please post some logs and more explanation on this. Keep in mind that we do not support such old framework as 2.0.10 anymore.

>  the server code should be backward compatible

It is. As I have already said, please post some logs and other explanation on issue, and keep in mind that we are only supporting latest releases.

**Comment by noizu** [comment]
My chat's been down for a few weeks. Did something change on the backend to kill support for 2.0.10? Realize it's an old SDK but bit of a pain to have to deal with breaking changes to increment the version if it's an backend issue. Our android app still works fine.

**Comment by Raikerian** [comment]
Hi @noizu 

Are you affiliated with issue creator? If yes, then the question here are you using dedicated enterprise instance or not?
There wasn't any changes that can possibly break your chat support.

**Comment by noizu** [comment]
Why do you guys just randomly kick accounts to force upgrades due to lack of support on standard ;). 
We've had an open tickets on this for over a week. The CEO wanted to stick with the product as we grow but I'm a little underwhelmed here. It's not hard to spin up a solution with phoenix/elixir.

**Comment by noizu** [comment]
The thing went pear shaped on us a few weeks back IOS only. remkohdev is digging into it further. but it's unusual as not coupled to any known code or infra changes on our end.  ^ _ ^

**Comment by Raikerian** [comment]
I don't really understand what is wrong with your account, can you elaborate with some details?
You have said that android app is working on the same backend, so can you at least provide some logs from iOS that indicate the problem?

> Why do you guys just randomly kick accounts to force upgrades due to lack of support on standard ;).

How are we kicking any accounts when you have clearly said that android app is working fine. If it was like that, it wouldn't work on android also.

Again, as this is iOS SDK repository, if you have some problems please attach logs that might indicate your problem.

**Comment by Raikerian** [comment]
Any updates?

**Comment by remkohdev** [comment]
I dont see the changelog for 2.0.10 to 2.1
The Result.h has disappeared, but I cannot find the documentation for it.

**Comment by Raikerian** [comment]
> My chat's been down for a few weeks.

I still haven't seen any updates on this, any logs or something with errors?

> The Result.h has disappeared, but I cannot find the documentation for it.

Might be a QBResponse you are looking at. As we are pretty much have interface based on blocks now, success block will always point out result. Check out our documentation: http://quickblox.com/developers/IOS#Code_samples

**Comment by Pro100Andrey** [comment]
@noizu , @remkohdev, any updates?
