### ISSUE TITLE
 Error: iOS WebRTC Video Chat

### ISSUE THREAD

**Issue by nikunjazilen** [QuickBlox/quickblox-ios-sdk#745]
Hi QuickBlox Team,

I am facing issue with my own configuration setup. I am testing the demo of ios webrtc video chat for video conference feature. When I set my credentials its not working and gives me error like "User's email is required" at login time.  So can you please resolve this issue? and tried with demo download credentials its working.

NSErrorFailingURLKey=https://api.quickblox.com/users.json, NSLocalizedDescription=Request failed: client error (422), com.alamofire.serialization.response.error.data=<7b226572 726f7273 223a5b22 55736572 27732065 6d61696c 20697320 72657175 69726564 225d7d>}
2017-02-02 11:58:58.960 sample-videochat-webrtc[627:140598] [QBCore] Response error reasons: {
    errors =     (
        "User's email is required"
    );

Demo Downloaded Credentials Working fine:
[QBSettings setAccountKey:@"7yvNe17TnjNUqDoPwfqp"];
[QBSettings setApplicationID:40718];
[QBSettings setAuthKey:@"AnB-JpA6r4y6RmS"];
[QBSettings setAuthSecret:@"3O7Sr5Pg4Qjexwn"];

Best Regards,
Nikunj Jadav

**Comment by Pro100Andrey** [comment]
Hi @nikunjazilen, please provide full logs

**Comment by nikunjazilen** [comment]
Hi Andrey,
Thanks for the update. Great work from your side to build this demo for developers 👍 
Issue has been resolved. There is permission required of email address and I checked it then its working fine. I have some queries regarding WebRTC Video Chat.
1) How many maximum users will be connected at a time while Video Conference?
2) Can user will be connect in existing Video Conference? For example, 3 users are connected in video conference then one more user want to join existing the video conference? Is it possible? bcoz I tried with this one but its automatically rejected. Can you please help me?
3) Can you please explain in details the Starter and Advance plan? Because I want to purchase Advance plan in future?
4) iOS WebRTC Video Chat source code available in Objective C. Is it available in Swift?

Thanks

**Comment by Raikerian** [comment]
Hi @nikunjazilen ,

1. It is hardly depends on device hardware and bandwidth.
2. You cannot do that for now, but we are working on it right now and it might be possible in a future.
3. Complete plan difference is represented on this page: https://quickblox.com/plans/
These are the only restrictions.
4. We do not have an example project in Swift, but our framework is fully compatible with Swift (version 2.4 is also dynamic framework with full bitcode support).

**Comment by nikunjazilen** [comment]
Hi Raikerian,

> We do not have an example project in Swift, but our framework is fully compatible with Swift (version 2.4 is also dynamic framework with full bitcode support).

As per your above message, iOS Pod QuickBlox and QuickBlox-WebRTC are compatible with Swift version 3.0? Please reply me so I can go ahead with you library.

Thanks.

**Comment by nikunjazilen** [comment]
Hi Raikerian,

I have one more query. Can QuickBlox provide video with text messaging feature in iOS? I tried with iOS WebRTC and Simple Chat Demo but its not working. Is it implemented any demo or sample available. If you give me last question, that will be great help for me.

Thanks.

**Comment by Raikerian** [comment]
> As per your above message, iOS Pod QuickBlox and QuickBlox-WebRTC are compatible with Swift version 3.0? Please reply me so I can go ahead with you library.

Use it as any other framework in swift, as I told it is fully compatible with swift.

> I have one more query. Can QuickBlox provide video with text messaging feature in iOS? I tried with iOS WebRTC and Simple Chat Demo but its not working. Is it implemented any demo or sample available. If you give me last question, that will be great help for me.

Don't really understand this request, do you want some messenger example where text chats and video chats are implemented? Take a look at our [Q-municate app](https://github.com/QuickBlox/q-municate-ios).

**Comment by nikunjazilen** [comment]
Hi,

Thanks for the reply. I just want to know Is it implemented text chat while video calling one to one/group video call like WhatsUp and Skype video calling.

**Comment by Raikerian** [comment]
Do you have any other specific questions on implementation? Basically our sample shows most of the things done, also check our our Q-municate (it has 2.3 SDK at this moment, but you can see most of the things implemented there too, such as notifications).

**Comment by nikunjazilen** [comment]
Hi Raikerian,

Now, not any other questions. If anything else I will update you. You can close this issue.

Thanks for the great support and help.

**Comment by Raikerian** [comment]
Let us know if you will have any other issues.

**Comment by optimumbrew** [comment]
[//]([url](url)) **Call other user (Click call button press)**

QBRTCClient.instance().add(self)
        let opponentsIDs = [38245148]
        let newSession = QBRTCClient.instance().createNewSession(withOpponents: opponentsIDs as [NSNumber], with: QBRTCConferenceType.video)
        // userInfo - the custom user information dictionary for the call. May be nil.
        let userInfo :[String:String] = ["key":"calling"]
        newSession.startCall(userInfo)
        print(userInfo)

//****************************

**above the code  some issue** : 

1.calling to the user but how to Accept the call ?
2. **opponentsIDs = [38245148]**  to call this user but login with  **[38245148]**  does not Receive call .

**Than call button press that log are as:** 

2017-12-07 15:51:20.988 rtc::[RTCClient] Added <DemoVideochat.VideoVC: 0x17ea2dd0> to list of delegates 
2017-12-07 15:51:20.989 rtc::[RTCClient] List of Delegates (
    "<DemoVideochat.VideoVC: 0x17ea2dd0>"
)
2017-12-07 15:51:20.990 rtc::[CAMC] Initializing QBRTCCameraCapture with video format: <QBRTCVideoFormat:0x17ea3880, dimensions: 640x480, frame rate: 30, pixel format: 420f>
2017-12-07 15:51:21.006 rtc::[CAMC] Starting QBRTCCameraCapture capture session.
2017-12-07 15:51:21.020619+0530 DemoVideochat[900:143132] [MC] System group container for systemgroup.com.apple.configurationprofiles path is /private/var/containers/Shared/SystemGroup/systemgroup.com.apple.configurationprofiles
2017-12-07 15:51:21.022288+0530 DemoVideochat[900:143132] [MC] Reading from public effective user settings.
2017-12-07 15:51:21.087 rtc::Updating device: <AVCaptureFigVideoDevice: 0x17dc4100 [Front Camera][com.apple.avfoundation.avcapturedevice.built-in_video:1]> with video format: <AVCaptureDeviceFormat: 0x17eae480 'vide'/'420f'  640x 480, { 2- 30 fps}, fov:54.370, max zoom:60.00 (upscales @2.00), ISO:29.0-928.0, SS:0.000028-0.500000>
2017-12-07 15:51:21.576 rtc::[CAMC] Capture session started.
2017-12-07 15:51:30.814 rtc::[RTCClient] Added <DemoVideochat.VideoVC: 0x17ea2dd0> to list of delegates 
2017-12-07 15:51:30.814 rtc::[RTCClient] List of Delegates (
    "<DemoVideochat.VideoVC: 0x17ea2dd0>"
)
2017-12-07 15:51:31.366 rtc::[RTCClient] You have to be logged in in order to use Chat API
["key": "calling"]
2017-12-07 15:58:04.421 rtc::[CAMC] Capture session interrupted: VideoDeviceNotAvailableInBackground
2017-12-07 15:58:04.421 rtc::[CAMC] Capture session stopped.


i am working swift and attach file 
[VideoVC.swift.zip](https://github.com/optimumbrew/videocall/files/1538773/VideoVC.swift.zip)





please solve the issue.

Thanks you

**Comment by Raikerian** [comment]
@optimumbrew Please create a new issue and explain it with much details as possible. Don't forget to check our [documentation](https://quickblox.com/developers/Sample-webrtc-ios) and [video sample](https://github.com/QuickBlox/quickblox-ios-sdk/tree/master/sample-videochat-webrtc).
