### ISSUE TITLE
Joining in an existing conference calls

### ISSUE THREAD

**Issue by iosgnanavel** [QuickBlox/quickblox-ios-sdk#856]
Hi Quickblox Team,

We are trying to join the new user into the existing video call. we  are retrieving session id from our server but not able to join the user into the call. Is there any possibility for joining the new user into the ongoing video call? (For Example:- A,B, C are in the conference video call  and now the D wants to join in the video call. How can we do this? we are having only the on-going call session id of the A,B,C.)

Thanks for advance.

**Comment by iosgnanavel** [comment]
Any updates?.

**Comment by Raikerian** [comment]
Hi,

You cannot join an existent call with our regular calls. As they are implemented as a peer to peer calls, all participants must be known at the moment of call, in order to connect to each other.
But we have custom enterprise solution with the usage of server-side, you can read more info here: https://quickblox.com/developers/EnterpriseFeatures#Conference_video_calls

**Comment by iosgnanavel** [comment]
Hi @Raikerian 

Thanks for your support
